### PR TITLE
Maxime-adjustments

### PR DESCRIPTION
**Pull request by quantitative-ecologist**
I updated the paragraph in "What we will explore" so that we now talk about consumer-resource interactions.

I also updated sections in the text, so now everything refers to consumer-resource instead of predator-prey, and to resource instead of prey.

### CODE REVIEW

**Comment by vmglynn** [comment]
Everything looks good!

**Review by vmglynn — APPROVED** [review]
All looks good!

**Comment by quantitative-ecologist** [comment]
I think you just need to merge to the main and everything should be fine. It appears that is is still not merged.

**Review by vmglynn — APPROVED** [review]
Looks good!

**Pull request merged**
